config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#index"
  get "/auth/github", as: :github_login
  get "/auth/github/callback", to: 'sessions#create'
  delete "/logout", to: 'sessions#destroy', as: :logout

  resources :github_users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/github_user.rb
class GithubUser < ApplicationRecord
  def self.from_omniauth(auth_info)
   where(uid: auth_info[:uid]).first_or_create do |new_user|
    new_user.uid                = auth_info["info"]["uid"]
    new_user.name               = auth_info["info"]["name"]
    new_user.user_name          = auth_info["info"]["nickname"]
    new_user.oauth_token        = auth_info["credentials"]["token"]
   end
  end
end

app/models/repo.rb
class Repo
  def initialize(name, language, created_at)
  @name = name
  @language = language
  @created_at = created_at
  end
  private
  attr_reader :name, :language, :created_at
end

app/models/starred.rb
class Starred
  def initialize(name, full_name)
    @name = name
    @full_name = full_name
  end
  private
  attr_reader :name, :full_name
end

app/models/user.rb
class User
  def initialize(login, url, uid, avatar_url)
    @login = login
    @url = url
    @uid = uid
    @avatar_url = avatar_url
  end

  private
  attr_reader :login, :url, :id, :avatar_url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= GithubUser.find_by(id: session[:user_id]) if session[:user_id]
  end

end

app/controllers/github_users_controller.rb
class GithubUsersController < ApplicationController
  def show
  @user_repo_presenter = UserRepoPresenter.new(current_user)

    @repositories = GithubService.new(current_user).fetch_repos
    @followers = GithubService.new(current_user).fetch_followers
    @following = GithubService.new(current_user).fetch_following
    @starred = GithubService.new(current_user).fetch_starred
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if user = GithubUser.from_omniauth(request.env["omniauth.auth"])
       session[:user_id] = user.id
    end
       redirect_to github_user_path(user.id)
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/github_users/show.html.erb
<h2><%= current_user.user_name %></h2><br>
<h4<%= current_user.name %></h4>

<h3> <% @user_repo_presenter.retrieve_user_repos. each do |repo| %>
  <li><%= @user_repo_presenter.display_titleized_repo_name(repo.name) %></li>
  <% end %>

<div class ="user_basics">
  <ul class="basics">
   <li class="repo>"> Repositories <%= @repositories.count%> </li>
   <li class="followers"> Followers <%= @followers.count%> </li>
   <li class="following"> Following <%= @following.count%> </li>
   <li class="starred"> Stars <%= @starred.count%> </li>
 </ul>
</div>

app/views/layouts/_navbar.html.erb
<% if current_user %>
  Hello, <%= current_user.user_name %>
<% else %>
  <%= link_to "Sign in with Github", github_login_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GitCloneProject</title>
    <%= csrf_meta_tags %>
  
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<% if current_user %>
  Hello, <%= current_user.user_name %><br>
  <%= link_to "Logout", logout_path, method: :delete %>
<% else %>
  <%= link_to "Sign in with Github", github_login_path %>
<% end %>